
openai:
  api:
    key:
      hj: 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

naver:
  ocr:
    key: Y3JkYlFXdWhIVElyVmtaSkRFSXFvd3ZXc0ZJa3RvQkc=
    url: https://sw1lx124fy.apigw.ntruss.com/custom/v1/49108/9708cbdcb85c65a885847cbced16046f4f0f3a218317f3f725e52ccfe754e92f/general
    